" vim defaults
set nocompatible

" only highlight diffs in vimdiff mode
if &diff
    syntax off
else
    syntax enable
endif

" display stuff
set showcmd
set showmatch
set showmode
set ruler
set nohls
let loaded_matchparen=1

" going with spaces
set expandtab

set tabstop=4
set softtabstop=0 " disable, default to tabstop
set shiftwidth=0 " disable, default to tabstop

" preferences, shortcuts, etc
set clipboard+=unnamed
map Y y$
set backspace=indent,start
noremap <Tab> :s/^/#/e<Enter><Enter>
noremap <S-Tab> :s/^#//e<Enter><Enter>

" indenting
vnoremap <S-Left> <gv
vnoremap <S-Right> >gv
nnoremap <S-Left> a<C-D><Esc>
nnoremap <S-Right> a<C-T><Esc>
inoremap <S-Left> <C-D>
inoremap <S-Right> <C-T>

" fix iterm2 cursor
if $TERM_PROGRAM =~ "iTerm.app"
    let &t_SI = "\<Esc>]50;CursorShape=1\x7" " Vertical bar in insert mode
    let &t_EI = "\<Esc>]50;CursorShape=0\x7" " Block in normal mode
endif


"" " vim-plug stuffs
"" let g:ycm_python_binary_path = 'python'
"" let g:ycm_complete_in_strings = 0
"" let g:ycm_autoclose_preview_window_after_insertion = 1
"" call plug#begin()
"" Plug 'scrooloose/nerdtree'
"" Plug 'Valloric/YouCompleteMe', { 'do': './install.py' }
"" call plug#end()
